language: csharp
dist: trusty

matrix:
  include:
    - mono: 5.18.0
      os: linux
    - mono: latest
      os: osx
      
sudo: true  # use the new container-based Travis infrastructure

script:
  - ./build.sh All

#allow_failures:
#    - mono: weekly
#      os: linux
#    - mono: nightly
#      os: linux
